# Generated by Django 4.0 on 2022-01-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
            ],
        ),
    ]
